### ISSUE TITLE
poned lineas horizontales

### ISSUE THREAD

**Issue by coyote3007** [ignaciobll/IngenieriaDelSoftware1#2]
en la parte de:
` \begin{figure}[h]
  \centering
  \begin{tabular}[h]{p{2.5cm} || p{3cm} | p{3cm} | p{5cm}}
    &\textbf{ADD}&\textbf{ACDM}&\textbf{Rozansky \& Woods} \\ \hline
    Mecánica y enfoque & Diseño iterativo descomponiendo elementos
                         recursivamente & Iteraciones de diseño,
                                          documentación y
                                          evaluación. & Iteraciones de diseño,
                                                        documentación y
                                                        evaluación. \\
    Participantes & Arquitecto & Arquitecto y otros & Arquitecto y
                                                      otros \\
    Entradas & Drivers & Drivers y alcance & Vistas \\
    Salidas & Esbozos de vistas & Vistas & Vistas \\
    Criterios de terminación & Se satisfacen los drivers & Los
                                                           experimentos
                                                           no revelan
                                                           riesgos o
                                                           son
                                                           aceptables
                               & Los interesados están de acerudo en
                                 que el diseño satisface sus
                                 preocupaciones. \\
    Conceptos de diseño utilizados & Técnicas y patrones & Estilos
                                                           arquitectónicos,
                                                           patrones y
                                                           prácticas &
                                                                       Estilos
                                                                       arquitectónicos
                                                                       y patrones.
    \end{tabular}  
  \caption[Comparación diseño arquitecturas]{Comparación de métodos de
    dieseño de arquitecturas}
  Interesante ver la figura \ref{fig:costemetodologia}
  \label{fig:comparaciondiseñoarquitectura}
\end{figure}`

insertad un 
`\cline{1-4}` 
para poder visualizar las celdas de forma horizontal con mayor facilidad

**Comment by ignaciobll** [comment]
Puestas 🤙
