### ISSUE TITLE
Escribid un potorro en alguna página

### ISSUE THREAD

**Issue by Cazaril** [ignaciobll/IngenieriaDelSoftware1#4]
Me parece un mal gesto que aún no haya ningún potorro en ninguna parte de este repositorio; Con este tipo de cosas le dais la razón a aquellas personas que creen que quereis derribar las tradiciones por todos queridas y los grandes momentos que estas nos han dado.

Quereis cambiar la forma de estudiar y crear un entorno más colaborativo, pasando por encima de las preferencias de los demás.

**Comment by samgh96** [comment]
WONTFIX
